task:
  name: Build Processor SDK
  container:
    image: ubuntu:22.04  # Use the appropriate base image for your build
  cache:
    folders:
      - .cache
      - tisdk/sources   # Caching the sources folder
      - tisdk/build     # Caching the build folder
  env:
    OEBASE: "/tmp/cirrus-ci-build/tisdk"
  install:
    - apt-get update
    - apt-get install -y \
        locales \
        git \
        build-essential \
        diffstat \
        texinfo \
        gawk \
        chrpath \
        socat \
        doxygen \
        dos2unix \
        python3 \
        bison \
        flex \
        libssl-dev \
        u-boot-tools \
        mono-devel \
        mono-complete \
        curl \
        python3-distutils \
        repo \
        pseudo \
        python3-sphinx \
        g++ \
        libc6-dev-i386 \
        jq \
        git-lfs \
        pigz \
        zstd \
        liblz4-tool \
        cpio \
        file \
        lz4

    # Generate locale
    - locale-gen en_US.UTF-8
    - update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

  script:
    - git clone https://git.ti.com/git/arago-project/oe-layersetup.git tisdk
    - cd tisdk
    - ./oe-layertool-setup.sh -f configs/processor-sdk-kirkstone-chromium-09.02.01.10-config.txt || exit 1
    - BITBAKEDIR=$(find "${OEBASE}/sources" -name "*bitbake*")
    - for f in ${BITBAKEDIR}; do
        if [ -d ${f}/bin ]; then
          PATH="${f}/bin:$PATH";
        fi;
      done
    - export PATH
    - export BUILDDIR="/tmp/cirrus-ci-build/tisdk/build"
    - export BB_ENV_PASSTHROUGH_ADDITIONS="MACHINE DISTRO TCMODE TCLIBC http_proxy ftp_proxy https_proxy all_proxy ALL_PROXY no_proxy SSH_AGENT_PID SSH_AUTH_SOCK BB_SRCREV_POLICY SDKMACHINE BB_NUMBER_THREADS PARALLEL_MAKE GIT_PROXY_COMMAND GIT_PROXY_IGNORE SOCKS5_PASSWD SOCKS5_USER OEBASE META_SDK_PATH TOOLCHAIN_TYPE TOOLCHAIN_BRAND TOOLCHAIN_BASE TOOLCHAIN_PATH TOOLCHAIN_PATH_ARMV5 TOOLCHAIN_PATH_ARMV7 TOOLCHAIN_PATH_ARMV8 EXTRA_TISDK_FILES TISDK_VERSION ARAGO_BRAND ARAGO_RT_ENABLE ARAGO_SYSTEST_ENABLE ARAGO_KERNEL_SUFFIX TI_SECURE_DEV_PKG_CAT TI_SECURE_DEV_PKG_AUTO TI_SECURE_DEV_PKG_K3 ARAGO_SYSVINIT SYSFW_FILE"
    - MACHINE=am62pxx-evm bitbake -k tisdk-default-image
